export const templateModalWindow = [
    {
        key: "project task",
        template: {
            name: true, 
            form: false,
            place: false,
            kind: true,
            tags: true, 
            dateTime: true,
            description: true, 
            descriptionUrl: true,
            eventURL: true,
            deadlinedateTime: true,
            deadlineDescription: true,
            organizer: true,
            duration: true,
            comment: true,
            isFeedback: true,
            feedback: true,
            materials: true,
            stage: true,    
        }
    },
    
    {
        key: "js task",
        template: {
            name: true,
            form: false,
            place: false,
            kind: true,
            tags: true,
            dateTime: true,
            description: true,
            descriptionUrl: true,
            eventURL: true,
            deadlinedateTime: true,
            deadlineDescription: true,
            organizer: true,
            duration: true,
            comment: true,
            isFeedback: true,
            feedback: true,
            materials: true,
            stage: true,    
        }
    },
    
    {
        key: "codewars",
        template: {
            name: true,
            form: false,
            place: false,
            kind: false,
            tags: true,
            dateTime: true,
            description: true,
            descriptionUrl: true,
            eventURL: false,
            deadlinedateTime: true,
            deadlineDescription: true,
            organizer: true,
            duration: false,
            comment: true,
            isFeedback: false,
            feedback: false,
            materials: false,
            stage: true,    
        }
    },

    {
        key: "test",
        template: {
            name: true,
            form: false,
            place: false,
            kind: false,
            tags: true,
            dateTime: true,
            description: true,
            descriptionUrl: false,
            eventURL: false,
            deadlinedateTime: true,
            deadlineDescription: false,
            organizer: true,
            duration: false,
            comment: true,
            isFeedback: false,
            feedback: false,
            materials: false,
            stage: true,   
        }
    },

    {
        key: "crosscheck",
        template: {
            name: true,
            form: false,
            place: false,
            kind: false,
            tags: true,
            dateTime: true,
            description: true,
            descriptionUrl: false,
            eventURL: true,
            deadlinedateTime: true,
            deadlineDescription: false,
            organizer: true,
            duration: false,
            comment: true,
            isFeedback: false,
            feedback: false,
            materials: false,
            stage: true,   
        }
    },

    {
        key: "review",
        template: {
            name: true,
            form: true,
            place: false,
            kind: false,
            tags: true,
            dateTime: true,
            description: true,
            descriptionUrl: false,
            eventURL: true,
            deadlinedateTime: false,
            deadlineDescription: false,
            organizer: true,
            duration: true,
            comment: true,
            isFeedback: false,
            feedback: false,
            materials: false,
            stage: true,          
        }
    },

    {
        key: "broadcast live",
        template: {
            name: true,
            form: true,
            place: false,
            kind: false,
            tags: true,
            dateTime: true,
            description: true,
            descriptionUrl: false,
            eventURL: true,
            deadlinedateTime: false,
            deadlineDescription: false,
            organizer: true,
            duration: true,
            comment: true,
            isFeedback: false,
            feedback: false,
            materials: true,
            stage: true,         
        }
    },

    {
        key: "self education",
        template: {
            name: true,
            form: false,
            place: false,
            kind: true,
            tags: true,
            dateTime: true,
            description: true,
            descriptionUrl: true,
            eventURL: false,
            deadlinedateTime: false,
            deadlineDescription: false,
            organizer: true,
            duration: false,
            comment: true,
            isFeedback: false,
            feedback: false,
            materials: true,
            stage: true,        
        }
    },

    {
        key: "meetup",
        template: {
            name: true,
            form: true,
            place: true,
            kind: false,
            tags: true,
            dateTime: true,
            description: true,
            descriptionUrl: true,
            eventURL: true,
            deadlinedateTime: false,
            deadlineDescription: false,
            organizer: true,
            duration: true,
            comment: true,
            isFeedback: true,
            feedback: false,
            materials: false,
            stage: false,        
        }
    },

    {
        key: "interview",
        template: {
            name: true,
            form: false,
            place: false,
            kind: true,
            tags: true,
            dateTime: true,
            description: true,
            descriptionUrl: true,
            eventURL: true,
            deadlinedateTime: true,
            deadlineDescription: true,
            organizer: true,
            duration: false,
            comment: true,
            isFeedback: true,
            feedback: true,
            materials: true,
            stage: true,          
        }
    },
    
    {
        key: "presentation",
        template: {
            name: true,
            form: true,
            place: true,
            kind: false,
            tags: true,
            dateTime: true,
            description: true,
            descriptionUrl: true,
            eventURL: true,
            deadlinedateTime: false,
            deadlineDescription: false,
            organizer: true,
            duration: false,
            comment: true,
            isFeedback: false,
            feedback: false,
            materials: true,
            stage: true,      
        }
    },
    {
        key: "other",
        template: {
            name: true,
            form: true,
            place: true,
            kind: true,
            tags: true,
            dateTime: true,
            description: true,
            descriptionUrl: true,
            eventURL: true,
            deadlinedateTime: true,
            deadlineDescription: true,
            organizer: true,
            duration: true,
            comment: true,
            isFeedback: true,
            feedback: true,
            materials: true,
            stage: true,        
        }
    }
]
  